"use client";
import { Poppins } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import NavbarFixed from './components/NavbarFixed/NavbarFixed'
import { usePathname } from 'next/navigation';

const font = Poppins({ subsets: ['latin'], weight: ["100" , "200", "300", "400", "500", "600", "700", "800", "900"] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={font.className}>
        {/* {<Navbar />} */}
        {["/services","/projects","/team","/contact","/partners"].includes(pathname) ? <NavbarFixed/> : <Navbar/>}
        {children}
        </body>
    </html>
  )
}
